### PR TITLE
added pr2

### PR DESCRIPTION
**Pull request by pashavinogr**

### CODE REVIEW

**Review by vitalygrischenko — COMMENTED** [review]
Use enuneration for constant params

**Review by vitalygrischenko — COMMENTED** [review]
See task

**Review by vitalygrischenko — APPROVED** [review]

**Review by vitalygrischenko — COMMENTED** [review]
more attentively see task

**Review by vitalygrischenko — COMMENTED** [review]
Enumeration separate class

**Review by vitalygrischenko — APPROVED** [review]
Ok

**Comment by pashavinogr** [comment]
why i can't merged this branch?

**Pull request merged**
